Pandas

1.   List item

In [1]:
import pandas as pd
import numpy as np

In [3]:
#python list to convert series
lis=[1,2,3,4,5]
series=pd.Series(lis)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [11]:
country=['bangladesh','india','nepal','Usa','canada']
pd.Series(country)

0    bangladesh
1         india
2         nepal
3           Usa
4        canada
dtype: object

In [12]:
run=[13,28,30,16,87,50,22,33]
d=pd.Series(run)

Series Index set

In [13]:
marks=[67,87,56.0,87]
subject=['bangla','math','ict','eng']
c=pd.Series(marks,index=subject)

Series Name

In [26]:
mark=[50,80,60,60,70]
subject=['bangla','english','Ict','math','science']
b=pd.Series(mark,index=subject,name='student mark list')

Series from dict

In [15]:
mark={'math':76,'english':87,'science':60,'hindi':100}
a=pd.Series(mark,name='student mark list')

Dtypes

Series attributes

Size

In [19]:
a.size

4

In [20]:
b.size

5

In [21]:
c.size

4

In [22]:
d.size

8

dtypes

In [23]:
a.dtypes

dtype('int64')

In [24]:
b.dtypes

dtype('int64')

Is Unique

In [25]:
a.is_unique

True

In [27]:
b.is_unique

False

In [28]:
a.index

Index(['math', 'english', 'science', 'hindi'], dtype='object')

In [29]:
a.values

array([ 76,  87,  60, 100])

Seies using read_csv

In [75]:
subs=pd.read_csv(r'/content/subs.csv')['Subscribers gained']

In [76]:
subs.head(5)

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [77]:
subs.sample()

319    158
Name: Subscribers gained, dtype: int64

In [78]:
subs.value_counts()

Subscribers gained
105    9
108    6
88     5
72     5
123    5
      ..
177    1
209    1
231    1
226    1
144    1
Name: count, Length: 180, dtype: int64

In [85]:
subs.sort_values(ascending=False).head()

330    396
331    312
168    306
233    301
280    295
Name: Subscribers gained, dtype: int64

In [59]:
runs=pd.read_csv(r'/content/kohli_ipl.csv',index_col='match_no',)['runs']

In [60]:
runs.head()

match_no
1     1
2    23
3    13
4    12
5     1
Name: runs, dtype: int64

In [61]:
runs.tail()

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [62]:
runs.sample()

match_no
65    36
Name: runs, dtype: int64

In [63]:
runs.value_counts( )

runs
0     9
1     8
12    8
9     7
8     6
     ..
46    1
29    1
84    1
90    1
53    1
Name: count, Length: 78, dtype: int64

In [83]:
runs.sort_values(ascending=False).head(5)

match_no
128    113
126    109
123    108
120    100
164    100
Name: runs, dtype: int64

In [90]:
runs.describe()

count    215.000000
mean      30.855814
std       26.229801
min        0.000000
25%        9.000000
50%       24.000000
75%       48.000000
max      113.000000
Name: runs, dtype: float64

In [66]:
movie=pd.read_csv(r'/content/bollywood.csv',index_col='movie')['lead']

In [67]:
movie.head()

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
Name: lead, dtype: object

In [68]:
movie.tail()

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [69]:
movie.sample()

movie
Namastey London    Akshay Kumar
Name: lead, dtype: object

In [70]:
movie.value_counts()

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64

In [87]:
movie.sort_values(ascending=False).head()

movie
Taj Mahal: An Eternal Love Story    Zulfi Sayed
Dil Toh Deewana Hai                 Zeenat Aman
Strings of Passion                  Zeenat Aman
Sallu Ki Shaadi                     Zeenat Aman
Dunno Y... Na Jaane Kyon            Zeenat Aman
Name: lead, dtype: object

In [88]:
movie.mode()

0    Akshay Kumar
Name: lead, dtype: object

In [89]:
run.describe()

AttributeError: 'list' object has no attribute 'describe'